### ISSUE TITLE
How to select other Cameras?

### ISSUE THREAD

**Issue by Diferno** [chuckfairy/node-webcam#11]
Hi! Awsome work by the way :+1: 

With the integrated webcam works like a charm, but I pluged a USB camera and can't figure out how to swap between cameras.

Any tip?

thx!

**Comment by zoutepopcorn** [comment]
In linux:
`var opts = {  width: 640,  height: 310,  delay: 0,  **device: "/dev/video1"**,  quality: 100,  output: "jpeg",  verbose: true };`

**Comment by moharm** [comment]
In Windows ?
