### ISSUE TITLE
Cant handle this saving error

### ISSUE THREAD

**Issue by vlisna789** [chuckfairy/node-webcam#16]
{ Error: Command failed: C:\Users\O77616\Documents\practiceCode\node_modules\nod
e-webcam\src\bindings\CommandCam\Commandcam.exe   /filename picofMe.jpg
'C:\Users\O77616\Documents\practiceCode\node_modules\node-webcam\src\bindings\Co
mmandCam\Commandcam.exe' is not recognized as an internal or external command,
operable program or batch file.

what does this mean?

**Comment by chuckfairy** [comment]
Does this file exist `C:\Users\O77616\Documents\practiceCode\node_modules\nod
e-webcam\src\bindings\CommandCam\Commandcam.exe` ? What is your setup? What shell / how are you running this? If possible try running Commandcam.exe alone and see what errors / outputs you get. Running this in DOS will not work. Thanks.

**Comment by MarekLani** [comment]
hi @chuckfairy I have the same issue but commandcam.exe does not exist. It is missing from module directory after npm install
