### ISSUE TITLE
It doesn't work when being called from server

### ISSUE THREAD

**Issue by astralcai** [chuckfairy/node-webcam#20]
`{ Error: Command failed: C:\Users\astra\Workspace\qhacks\node_modules\node-webcam\src\bindings\CommandCam\Commandcam.exe   /filename ./images/image1517735395599.jpg
Capture device: USB Video Device
Error: 2147943850
Could not run filter graph

    at ChildProcess.exithandler (child_process.js:198:12)
    at emitTwo (events.js:106:13)
    at ChildProcess.emit (events.js:191:7)
    at maybeClose (internal/child_process.js:920:16)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:230:5)
  killed: false,
  code: 1,
  signal: null,
  cmd: 'C:\\Users\\astra\\Workspace\\qhacks\\node_modules\\node-webcam\\src\\bindings\\CommandCam\\Commandcam.exe   /filename ./images/image1517735395599.jpg' }
`

**Comment by chuckfairy** [comment]
You are running this on a windows server? I'm trying to see what I should test with. That error gets me a Task Schedule error have you tried anything on this? https://answers.microsoft.com/en-us/windows/forum/windows_7-windows_programs/task-scheduler-failed-to-start-error-2147943850/e79d7d4d-6878-4ad2-bef2-6a4733ff8793

A lot of searches result in an app called GraphEdit. Maybe there are some libraries in that that will help.
