### ISSUE TITLE
I ran this on a mac (Sierra 10.13) and it doesn't save 

### ISSUE THREAD

**Issue by csanz** [chuckfairy/node-webcam#21]
Sounds like imagesnap doesn't work with the latest version of Apple's OS (Sierra 10.13)... if you run imagesnap test.jpg -v  on the terminal it won't output anything, but you'll see the light from the camera come on, so something is working, but it is not saving to disc.  Any workaround?

**Comment by nmsdvid** [comment]
I'm having the same issue on Sierra 10.12.6. So far what i could figure out is that when you set a time interval it saves the image locally. For example, imagesnap -t 1 test.jpg -v

**Comment by chuckfairy** [comment]
@nmsdvid Is right it needs an interval on Mac. I force the delay because of this https://github.com/chuckfairy/node-webcam/blob/master/src/webcams/ImageSnapWebcam.js#L34. Is node-webcam itself not adding the delay? If it's a bug I can fix, but it needs the interval.
