### ISSUE TITLE
Just a question

### ISSUE THREAD

**Issue by stherrienaspnet** [chuckfairy/node-webcam#23]
How would you take a capture from 2 cameras on the same time?
When using this way I end up with only one file writen on the disk 'my_picture_cam1'

var Webcam = NodeWebcam.create( opts );
Webcam.list( function( list ) {

    NodeWebcam.capture( "my_picture_cam1", { device: list[ 0 ] }, function( err, data ) {    
        if ( !err ) console.log( "Image created cam1 !" );
    });

    NodeWebcam.capture( "my_picture_cam2", { device: list[ 1 ] }, function( err, data ) {   
        if ( !err ) console.log( "Image created cam2!" );     
    });

});

What would be the way to picture from my 2 camera on the same time?
The closest I can get is 2 seconds when starting the camera 2 capture inside camera1 callback.

Thanks you for your help :)

**Comment by chuckfairy** [comment]
fswebcam which is what linux will use by default will not allow multiple at the same time. All platforms should be the same unfortunately. It's something I hope to have though, once a C++ addon is created.
