### ISSUE TITLE
Typo?  `require( "./../../" );`

### ISSUE THREAD

**Issue by JamesNewton** [chuckfairy/node-webcam#26]
On [line 34 of /examples/websocket/App.js](https://github.com/chuckfairy/node-webcam/blob/master/examples/websocket/App.js#L34), the require is given a parameter of "./../../" which can't be right... 

`var NodeWebcam = require( "./../../" );`

should be

`var NodeWebcam = require( "node-webcam" );`

No?

**Comment by chuckfairy** [comment]
You as an end user would use the later and I can add a note in the example about this. However for testing and usage without installing itself in the repo, we use that to include it in the examples.
