### ISSUE TITLE
Capture multiple webcam on Linux?

### ISSUE THREAD

**Issue by sweetim** [chuckfairy/node-webcam#4]
How can I configure the camera path for this module?

I have multiple webcam connected to my Linux pc

**Comment by chuckfairy** [comment]
You can use the `Webcam.list( callback( list ) )` function to generate an array of strings you can use to pass as an option in the Webcam constructor `new Webcam({ device: list[0] }) || NodeWebcam.capture( location, { device: list[0] }, callback )`. See [test/list_cameras.js](https://github.com/chuckfairy/node-webcam/blob/master/test/list_cameras.js). As for doing this asynchronously on Linux, I have not had luck with fswebcam, the current program used. It could have been my implementation though at the time. Looking into solutions.
