### ISSUE TITLE
No option for frame rate

### ISSUE THREAD

**Issue by santu9** [chuckfairy/node-webcam#42]
FSwebcam can take framerate option too. May be include that option while creating webcam instance?

**fswebcam -F 60 -r 1024x768**

**Comment by chuckfairy** [comment]
We can add that feature. Probably name it number_of_frames so we don't conflict with a possible framerate config when we add video support.

**Comment by chuckfairy** [comment]
https://github.com/chuckfairy/node-webcam/pull/43
