### ISSUE TITLE
Capturing error while displaying camera view in browser.

### ISSUE THREAD

**Issue by navinak** [chuckfairy/node-webcam#5]
I tried to display camera view using HTML5.
`var video = document.getElementById('video');
if(navigator.mediaDevices && navigator.mediaDevices.getUserMedia) {
    navigator.mediaDevices.getUserMedia({ video: true }).then(function(stream) {
        video.src = window.URL.createObjectURL(stream);
        video.play();
    });
}` 

Above code displaying camera view in browser.But capturing is not working because of camera resource is already busy.
so how to display camera view while capturing using node-webcam.

**Comment by chuckfairy** [comment]
If the camera resource is busy from using it in the browser, you'll probably not be able to use node-webcam at the same time. If you're asking how you view from the browser with node-webcam, I did put up an example here https://github.com/chuckfairy/node-webcam/tree/master/examples/websocket  using websockets. Basically just capture a shot as base64 and send it to the browser.
