### ISSUE TITLE
TS Types

### ISSUE THREAD

**Issue by Atgoogat** [chuckfairy/node-webcam#56]
It would be useful if there would be support for Typescript Types.

**Comment by lordazzi** [comment]
I've created a @types/node-webcam, here is the pull request: https://github.com/DefinitelyTyped/DefinitelyTyped/pull/64289

**Comment by lordazzi** [comment]
https://www.npmjs.com/package/@types/node-webcam

**Comment by Atgoogat** [comment]
Thanks a lot!
