### ISSUE TITLE
capture image with location version doesnt work

### ISSUE THREAD

**Issue by antantanthony** [chuckfairy/node-webcam#9]
in Webcam.js

`var location = location || "";`
seems doesnt getting my location flag in opts

could you fix it ?
my temp fix is as below
`var location = scope.opts.location + location || "";`

Please verify :)

**Comment by chuckfairy** [comment]
You pass in location of the image in the capture function. see 

https://github.com/chuckfairy/node-webcam#webcamcapture-string-location-object-options-function-callback- 
https://github.com/chuckfairy/node-webcam#nodewebcamcapture-string-location-object-options-function-callback-

**Comment by antantanthony** [comment]
oh yes, thanks
however, what is `location` means or actual do in option 
https://github.com/chuckfairy/node-webcam#usage
Thanks

**Comment by chuckfairy** [comment]
It's the keyword for the shell usage. shorthands listed below it.
